/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controllers.EmployeeController;
import Models.Employee;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @author moham
 */
public class EmployeeView extends JFrame {
    private EmployeeController employeeController = new EmployeeController();

    /**
     * Creates new form EmployeeView
     */
    public EmployeeView() {
        initComponents();
        displayAllEmployees();
    }

    private void displayAllEmployees() {

        List<Employee> employees = employeeController.findAllEmployees();


        DefaultTableModel model = (DefaultTableModel) empTable.getModel();


        model.setRowCount(0);


        for (Employee employee : employees) {

            Object[] row = new Object[] {
                    employee.getEmpID(),
                    employee.getEmpName(),
                    employee.getPosition(),
                    employee.getNic(),
                    employee.getPhone(),
                    employee.getAddress(),
                    employee.getEmail(),
                    employee.getSalary()
            };


            model.addRow(row);
        }


        empTable.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new JPanel();
        jPanel1 = new JPanel();
        jButton1 = new JButton();
        jButton2 = new JButton();
        jButton3 = new JButton();
        sidebarEmpBtn = new JButton();
        jButton5 = new JButton();
        jButton6 = new JButton();
        jLabel3 = new JLabel();
        jLabel1 = new JLabel();
        jScrollPane1 = new JScrollPane();
        empTable = new JTable();
        searchField = new JTextField();
        searchButton = new JButton();
        searchCriteria = new JComboBox<>();
        addNewEmpbtn = new JButton();
        empUpdateDelete = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jButton1.setText("Orders");

        jButton2.setText("Suppliers");

        jButton3.setText("Inventory");

        sidebarEmpBtn.setText("Employees");
        sidebarEmpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sidebarEmpBtnActionPerformed(evt);
            }
        });

        jButton5.setText("Assign Jobs");

        jButton6.setText("Reports");

        jLabel3.setIcon(new ImageIcon(getClass().getResource("/images/carcare-high-resolution-logo-transparent.png"))); // NOI18N

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sidebarEmpBtn, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(jButton6, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 138, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(sidebarEmpBtn, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jButton5, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jButton6, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Employee Management");

        empTable.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        empTable.setModel(new DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "EmployeeID", "Name", "Position", "NIC", "Phone", "Address", "Email", "Salary"
                }
        ));
        empTable.setToolTipText("");
        empTable.setRowHeight(25);
        jScrollPane1.setViewportView(empTable);

        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empSearchFieldActionPerformed(evt);
            }
        });

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        searchCriteria.setModel(new DefaultComboBoxModel<>(new String[] { "EmpID", "Name"}));
        searchCriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCriteriaActionPerformed(evt);
            }
        });

        addNewEmpbtn.setBackground(new java.awt.Color(0, 204, 102));
        addNewEmpbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addNewEmpbtn.setForeground(new java.awt.Color(255, 255, 255));
        addNewEmpbtn.setText("Add New Employee");
        addNewEmpbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewEmpbtnActionPerformed(evt);
            }
        });

        empUpdateDelete.setText("Update/Delete");

        empUpdateDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empUpdateDeleteActionPerformed(evt);
            }
        });

        GroupLayout jPanel3Layout = new GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 1006, GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(searchField, GroupLayout.PREFERRED_SIZE, 577, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchCriteria, GroupLayout.PREFERRED_SIZE, 124, GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchButton, GroupLayout.PREFERRED_SIZE, 122, GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(empUpdateDelete, GroupLayout.PREFERRED_SIZE, 135, GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(78, 78, 78)
                        .addComponent(addNewEmpbtn, GroupLayout.PREFERRED_SIZE, 273, GroupLayout.PREFERRED_SIZE)))
                .addGap(108, 108, 108))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 97, GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(addNewEmpbtn, GroupLayout.PREFERRED_SIZE, 48, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addGroup(GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(empUpdateDelete, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchButton, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE))
                    .addComponent(searchCriteria)
                    .addComponent(searchField))
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchCriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCriteriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchCriteriaActionPerformed

    private void empSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empSearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empSearchFieldActionPerformed

    private void empUpdateDeleteActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String criteria = searchCriteria.getSelectedItem().toString();
        String searchText = searchField.getText();

        try {
            if (criteria.equals("EmpID")) {
                int empID = Integer.parseInt(searchText);
                Employee employee = employeeController.findEmployeeById(empID);
                if (employee != null) {
                    EmployeeUpdateView updateView = new EmployeeUpdateView();
                    updateView.populateFields(employee);
                    updateView.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "No employee found with the provided EmpID.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else if (criteria.equals("Name")) {
                List<Employee> employees = employeeController.findEmployeesByName(searchText);
                displayEmployeesInTable(employees);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid input. Please enter a valid number.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        String criteria = searchCriteria.getSelectedItem().toString();
        String searchText = searchField.getText();

        try {
            if (criteria.equals("EmpID")) {
                int empID = Integer.parseInt(searchText);
                Employee employee = employeeController.findEmployeeById(empID);
                displayEmployeeInTable(employee);
            } else if (criteria.equals("Name")) {
                List<Employee> employees = employeeController.findEmployeesByName(searchText);
                displayEmployeesInTable(employees);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid input. Please enter a valid number.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void displayEmployeeInTable(Employee employee) {
        DefaultTableModel model = (DefaultTableModel) empTable.getModel();
        model.setRowCount(0);
        addEmployeeToTable(employee, model);
    }

    private void displayEmployeesInTable(List<Employee> employees) {
        DefaultTableModel model = (DefaultTableModel) empTable.getModel();
        model.setRowCount(0);
        for (Employee employee : employees) {
            addEmployeeToTable(employee, model);
        }
    }

    private void addEmployeeToTable(Employee employee, DefaultTableModel model) {
        Object[] row = new Object[] {
                employee.getEmpID(),
                employee.getEmpName(),
                employee.getPosition(),
                employee.getNic(),
                employee.getPhone(),
                employee.getAddress(),
                employee.getEmail(),
                employee.getSalary()
        };
        model.addRow(row);
    }

    private void addNewEmpbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewEmpbtnActionPerformed
        // TODO add your handling code here:
        
            AddEmployeeView empdetails = new AddEmployeeView();
            empdetails.show();
            
        
    }//GEN-LAST:event_addNewEmpbtnActionPerformed

    private void sidebarEmpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sidebarEmpBtnActionPerformed
        // TODO add your handling code here;
        displayAllEmployees();

    }//GEN-LAST:event_sidebarEmpBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton addNewEmpbtn;
    private JTextField searchField;
    private JTable empTable;
    private JButton empUpdateDelete;
    private JButton jButton1;
    private JButton jButton2;
    private JButton jButton3;
    private JButton jButton5;
    private JButton jButton6;
    private JLabel jLabel1;
    private JLabel jLabel3;
    private JPanel jPanel1;
    private JPanel jPanel3;
    private JScrollPane jScrollPane1;
    private JButton searchButton;
    private JComboBox<String> searchCriteria;
    private JButton sidebarEmpBtn;
    // End of variables declaration//GEN-END:variables
}
